server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

database:
  driverClass: org.h2.Driver
  url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  user: sa
  password: 

logging:
  level: INFO
  appenders:
    - type: console
      logFormat: "[%d{yyyy-MM-dd HH:mm:ss}] [%p] %c{1} - %m%n"